name: jooq-kotlin-2-example

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      id: setup-java
      uses: actions/setup-java@v4
      with:
        distribution: "corretto"
        java-version: "21"

    - name: Tell Gradle where the Java installation is
      run: |
        echo "org.gradle.java.installations.paths=${{ steps.setup-java.outputs.path }}" >> gradle.properties

    - name: Cache dependencies
      id: cache-gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle
          ~/.m2
        key: 1-${{ hashFiles('*.gradle.kts', 'gradle.properties') }}

    - name: Download dependencies
      run: |
        docker pull postgres:13

    - name: Compile main
      run: ./gradlew classes
